checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    coverage:
      tests:
        override:
           - command: './scripts/run-tests.sh'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'